GET  http://localhost:3000/users;
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmFsYWppZ3YiLCJpYXQiOjE2MjM5OTcxMDF9.7hPY7lhpaD-hColFZgWmc2nkhoXoDSGAWyaeBe_PWZU
###


POST  http://localhost:3000/users
Content-Type: : application/json


{
    "username":"balaji",
    "password":"Balajigv25@"
}

###
POST  http://localhost:3000/users/login
Content-Type: : application/json


{
    "username":"balaji",
    "password":"Balajigv25@"
}